### ISSUE TITLE
Memory leak, bad allocation, segfault problems

### ISSUE THREAD

**Issue by smcameron** [kilbouri/terminal-3d#1]
Hey, I'm participating in hacktoberfest 2021 to get a free t-shirt, and I have 4 patches for your project to add a Makefile, fix a memory leak, fix a bad allocation, and fix a segfault.  Can you add the "hacktoberfest" tag to your project  (By "About, click the gear icon, and add "hacktoberfest" to the topics).  Whether the answer is "yes" or "no", I'll send you the patches in either case.

**Comment by kilbouri** [comment]
Unfortunately this version is outdated and I've nearly completely rewritten it from the ground up. 

I haven't pushed the changes yet so I'll take the patches anyways.

**Comment by smcameron** [comment]
Thanks. I've submitted a pull request.
